# Generated by Django 5.0.6 on 2024-07-22 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_personal', models.IntegerField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('tipo_usuario', models.CharField(choices=[('arrendatario', 'arrendatario'), ('arrendador', 'arrendador')], max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('m2_construidos', models.FloatField()),
                ('m2_totales', models.FloatField()),
                ('cantidad_estacionamientos', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField()),
                ('cantidad_banos', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('tipo_inmueble', models.CharField(choices=[('casa', 'casa'), ('departamento', 'departamento'), ('parcela', 'parcela')], max_length=20)),
                ('precio_arriendo', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('solicitudes', models.JSONField(blank=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='m7_python.comuna')),
                ('arrendatario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrendatario', to='m7_python.usuario')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='m7_python.usuario')),
            ],
        ),
    ]
