# Generated by Django 5.0.6 on 2024-08-02 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_remove_usuario_apellido_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arrendatario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrendatario', to='m7_python.usuario'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='solicitudes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
